language: node_js

before_install:
  - "Xvfb :99 -ac -screen 0 1280x1024x24 &"
  - sleep 3
  - "export DISPLAY=:99"
  - "npm install se-interpreter -g"
  - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.0.jar"
  - "java -jar selenium-server-standalone-2.43.0.jar &"
  - sleep 3
  
  
script:
  - "se-interpreter ./settingsPage/layoutBuilder_pluginsManagerTest.json"
