language: node_js

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install --production selenium-standalone@latest -g"
  - "npm install -g se-interpreter"
  - "start-selenium"

  
script:
  - "se-interpreter ./settingsPage/layoutBuilder_pluginsManagerTest.json"
