language: node_js

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3
  - "npm install se-interpreter -g"
  - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.0.jar"
  - "java -jar selenium-server-standalone-2.43.0.jar &"
  - sleep 3
  
  
script:
  - "se-interpreter --start-maximized --browser-browserName=chrome ./settingsPage/layoutBuilder_pluginsManagerTest.json"
