language: node_js

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 1
  - "npm install string wd glob optimist"
  - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.0.jar"
  - "java -jar selenium-server-standalone-2.43.0.jar &"
  - sleep 1
  
  
script:
  - "./se-interpreter.sh ./settingsPage/layoutBuilder_pluginsManagerTest.json"
